website/views.py
##routes for website
import sqlalchemy
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, jsonify, make_response
from . import db
import json
import pdfkit


from .models import Patient, Appointment, Specification, Role, HospitalStaff, AvailabilitySchedule,SystemConfig,TimeSlot, Room, Prescription,PrescriptionContent,RoomBooking,Medicine, Diagnose, Disease, InvoiceRecord, Payment, Invoice


from .auth import check_session
from sqlalchemy import text
from sqlalchemy.sql import func
from datetime import datetime, timedelta
from werkzeug.security import generate_password_hash,check_password_hash



views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    if check_session()["Logged_In"] != False and check_session()["Role"] == "Patient":
        patientID = session["Patient_ID"]
        user = Patient.query.filter_by(Patient_ID=patientID).first()
        return render_template("profile.html", patient=user, role="patient")
    elif check_session()["Logged_In"] != False and check_session()["Role"] != "Patient" and check_session()["Role"] != "Admin":
        doctorID = session["Staff_ID"]
        doctor = HospitalStaff.query.filter_by(Staff_ID = doctorID).first()
        return render_template("staff_profile.html", staff=doctor, role = "staff")
    elif check_session()["Logged_In"] != False and check_session()["Role"] == "Admin":
        email = session["Admin_E-Mail"]
        system_admin = SystemConfig.query.filter_by(Admin_E_Mail=email).first()
        return render_template("admin.html", role="admin", admin=system_admin)
    else:
        return redirect(url_for('auth.login'))



@views.route('/invoices', methods=['GET', 'POST'])
def invoices():
    if check_session()["Logged_In"] != False and check_session()["Role"] != "Patient" and request.method != 'POST':
        # ("staff or admin user visiting appointments view")
        staff = session['Staff_ID']
        sql = text("select * from V_Invoices")
        invoices = db.engine.execute(sql)
        return render_template("invoices.html", role="staff", staff=staff, invoices = invoices)
    else:
        return redirect(url_for('views.appointments'))

##invoice records -> json output

@views.route('/invoice_records', methods = ['GET'])
def invoice_records():
    if check_session()["Logged_In"] != False and check_session()["Role"] != "Patient":
        inv_no = request.args.get("Invoice_Number")

        invoice_records = InvoiceRecord.query.filter_by(Invoice_Number = inv_no).all()

        all_records = [{
                        'date' : str(datetime.strftime(record.Create_Date, '%d-%m-%Y %H:%M')),
                        'record_id': str(record.Record_ID),
                        'invoice_number': str(record.Invoice_Number),
                        'staff_id': record.Hospital_Staff.Name + " " + record.Hospital_Staff.Surname + " (ID:"+str(record.Hospital_Staff.Staff_ID)+")",
                        'description': str(record.Description),
                        'amount': str(record.Amount)
                          } for record in invoice_records]
        return jsonify(all_records)
    elif check_session()["Logged_In"] != False and check_session()["Role"] == "Patient":
        inv_no = request.args.get("Invoice_Number")
        patient_id = session.get("Patient_ID")
        invoice = Invoice.query.filter_by(Invoice_Number=inv_no, Patient_ID = patient_id).all()
        if invoice:
            #if that invoice is actually assigned to logged in patient
          invoice_records = InvoiceRecord.query.filter_by(Invoice_Number=inv_no).all()

        all_records = [{
            'date': str(datetime.strftime(record.Create_Date, '%d-%m-%Y %H:%M')),
            'record_id': str(record.Record_ID),
            'invoice_number': str(record.Invoice_Number),
            'staff_id': record.Hospital_Staff.Name + " " + record.Hospital_Staff.Surname + " (ID:" + str(
                record.Hospital_Staff.Staff_ID) + ")",
            'description': str(record.Description),
            'amount': str(record.Amount)
        } for record in invoice_records]
        return jsonify(all_records)

    else:
        return redirect(url_for('auth.login'))


@views.route('/payments', methods = ['GET'])
def invoice_payments():
    if check_session()["Logged_In"] != False and check_session()["Role"] != "Patient":
        inv_no = request.args.get("Invoice_Number")

        payments = Payment.query.filter_by(Invoice_Number = inv_no).all()


        all_records = [{
                        'date' : str(datetime.strftime(record.Payment_Date, '%d-%m-%Y %H:%M')),
                        'payment_id': str(record.Payment_ID),
                        'description': str(record.Description),
                        'amount': str(record.Payment_Amount),
                        'type': str(record.Type),
                         'staff': str(record.Hospital_Staff.Name) + " " + str(record.Hospital_Staff.Surname) + " ID: " + str(record.Hospital_Staff.Staff_ID)
                          } for record in payments]
        return jsonify(all_records)
    elif check_session()["Logged_In"] != False and check_session()["Role"] == "Patient":

        inv_no = request.args.get("Invoice_Number")
        patient_id = session.get("Patient_ID")
        invoice = Invoice.query.filter_by(Invoice_Number=inv_no, Patient_ID=patient_id).all()
        payments = Payment.query.filter_by(Invoice_Number=inv_no).all()
        if invoice:
            all_records = [{
                'date': str(datetime.strftime(record.Payment_Date, '%d-%m-%Y %H:%M')),
                'payment_id': str(record.Payment_ID),
                'description': str(record.Description),
                'amount': str(record.Payment_Amount),
                'staff': str(record.Hospital_Staff.Name) + " " + str(record.Hospital_Staff.Surname) + " ID: " + str(
                    record.Hospital_Staff.Staff_ID)
            } for record in payments]


            return jsonify(all_records)


    else:
        return redirect(url_for('auth.login'))

@views.route('/add_invoice', methods = ['POST'])
def add_invoice():
    staff = session['Staff_ID']
    if check_session()["Logged_In"] != False and check_session()["Role"] != "Patient" and request.method == 'POST':
        data = json.loads(request.data)
        patient_id = data["Patient_ID"]
        due_date  = data["Due_Date"]

        due_date = datetime.strptime(due_date, "%d/%m/%Y")

        new_invoice = Invoice(Patient_ID = patient_id, Due_Date = due_date ,Creation_Date = func.now())
        db.session.add(new_invoice)
        db.session.commit()

        print(patient_id, due_date)
        return render_template("add_payment.html", role="staff", staff=staff)
    else:
        return redirect(url_for('views.home'))




##staff route
@views.route('/staff', methods=['GET', 'POST'])
def staff():
    if check_session()["Logged_In"] != False and check_session()["Role"] == "Patient":
        #patientID = session["Patient_ID"]
       # user = Patient.query.filter_by(Patient_ID=patientID).first()
        return redirect(url_for('views.home'))
    elif check_session()["Logged_In"] != False and check_session()["Role"] != "Patient":
        doctorID = session["Staff_ID"]
        doctor = HospitalStaff.query.filter_by(Staff_ID = doctorID).first()
        return render_template("staff_profile.html", role="staff", staff=doctor, patient= None)
    else:
        return redirect(url_for('views.home'))


@views.route('/manage', methods=['GET', 'POST'])
def showstaff():
    if check_session()["Logged_In"] != False and check_session()["Role"] == "Admin":
        if request.method == 'POST':
            if request.form.get('Specification_ID') == "2":
                rt = 2
            elif request.form.get('Specification_ID') == "3":
                rt = 3
            elif request.form.get('Specification_ID') == "4":
                rt = 4
            else:
                rt = 1

            if request.form.get('Role') == "2":
                rt = 2
            else:
                rt = 1

            new_staff = HospitalStaff(
                            Name=request.form.get('Name'),
                            Surname=request.form.get('Surname'),
                            Specification_ID=request.form.get('Specification_ID'),
                            Role=request.form.get('Role'),
                            EMail=request.form.get('EMail'),
                            Password = generate_password_hash(request.form.get('Password'), method='sha256')
                              )


            db.session.add(new_staff)
            db.session.commit()

            Hospital_Staff = db.session.query(HospitalStaff).all()
            return render_template('manage.html', Hospital_Staff=Hospital_Staff, role="admin")
        all_specifications = Specification.query.all()
        roles = Role.query.all()
        Hospital_Staff = db.session.query(HospitalStaff).all()
        return render_template('manage.html', Hospital_Staff=Hospital_Staff, role="admin", specifications = all_specifications, roles= roles)

@views.route('/deletestaff/<int:id>', methods=['POST'])
def deletestaff(id):
    if check_session()["Logged_In"] != False and check_session()["Role"] != "Patient":
        staff_to_delete = db.session.query(HospitalStaff).get(id)
        db.session.delete(staff_to_delete)
        db.session.commit()
        return redirect('/manage')

#create new prescription
@views.route('/create_prescription', methods = ['POST'])
def create_prescription():
    if request.method == "POST" and check_session()["Logged_In"] != False and check_session()["Role"] != "Patient":
        data = json.loads(request.data)
        Patient_ID = data['Patient_ID']
        Staff_ID = data['Staff_ID']
        ##check if there is a patient and a staff with that id
        patient = Patient.query.filter_by(Patient_ID = Patient_ID).first()

website/templates/add_record.html
{% extends "base_no_sidebar.html" %}


{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet">

    <link href="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}




                      <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Add Record Into Invoice</h6>
                        </div>
                        <div class="card-body">





                            <form>
  <div class="form-group">
  <input type="hidden" id="Invoice_Number" name="Invoice_Number" value="" />

      <label>Description</label>
      <input type="text" class="form-control" name="description" id="description">
      <hr>
      <label>Amount</label>
      <input type="number" max="10000.00" step="0.01" class="form-control" name="amount" id="amount">
      <hr>


  <button onclick="addRecord()" class="btn btn-success"><span aria-hidden="true">Add</span></button>


  </div>


</form>



                        </div>
                    </div>

<div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" style="border:0!important;" id="contentTable" width="100%" cellspacing="0">

                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>


{% endblock %}

{% block scripts %}

       <!-- Page level plugins -->
    <script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ url_for('static', filename='main.js') }}"></script>
    <script src="{{ url_for('static', filename='populate.js') }}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
<script>






function addRecord() {

    var Invoice_Number = getUrlParameter('Invoice_Number')

    $("#Invoice_Number").val(Invoice_Number);
    var description = $('#description').val();
    var amount = $('#amount').val();
  fetch("/add_record", {
    method: "POST",
    body: JSON.stringify({ Invoice_Number: Invoice_Number, Description :description, Amount: amount  }),
  }).then((_res) => {
    location.reload();
     updateRecords();
  });
}



function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if ( (charCode > 31 && charCode < 48) || charCode > 57) {
            return false;
        }
        return true;
    }
</script>
<script>
var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = window.location.search.substring(1),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : decodeURIComponent(sParameterName[1]);
        }
    }
    return false;
};
function updateRecords(){
        var Invoice_Number = getUrlParameter('Invoice_Number')
        if (Invoice_Number != "0") {

            var value = Invoice_Number;
             $.ajax({
            type: 'GET',
            url: "/invoice_records?Invoice_Number="+value,
            //data: { Specification: Specification },
            contentType: 'application/json',
            dataType: 'json',
            success: function(response) {
                        $("#contentTable").empty();
                       console.log(response)
                       output  = ``;
                   if (response.length > 0){

                      $.each(response, function(a,b){

                          output += "<tr>" +
                          "<td><b>Date: </b>" + b.date + "</td>" +
                              "<td><b>Description: </b>" + b.description + "</td>" +
                              "<td><b>Amount: </b>" + b.amount + " EUR</td>" +
                              "<td><b>Staff: </b>" + b.staff_id + "</td>" +

                          "</tr>"
                   })

                   }
 $("#contentTable").empty();
             $("#contentTable").append(output);
            }

        });









        }






    }


</script>
<script>
$( document ).ready(function() {
    updateRecords()
});
</script>

{% endblock %}

website/templates/admin.html
{% extends "base.html" %}
{% block title %}Admin Panel{% endblock %}
{% block content %}


                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Admin</h1>

        <div class="row">
             <div class="col-lg-8">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Admin Homepage</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Position</th>

                                        </tr>
                                    </thead>

                                    <tbody>

                                     <tr>
                                            <td>Specification</td>
                                            <td>Admin</td>
                                     </tr>




                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
        </div>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}[Home]{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->

    <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">

    {% block head %}

    {% endblock %}
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laptop-medical"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SDP<sup>Medical</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

    {% if role == "admin" %}
         <li class="nav-item">
                <a class="nav-link" href="/">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Admin Home</span></a>
            </li>

        <li class="nav-item">
                <a class="nav-link" href="/rooms">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Manage Rooms</span></a>
            </li>

        <li class="nav-item">
                <a class="nav-link" href="/manage">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Manage Saff</span></a>
            </li>


 {% elif role == "staff" %}
         <li class="nav-item">
                <a class="nav-link" href="/">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Home</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/schedule">
                    <i class="fas fa-fw fa-calendar-day"></i>
                    <span>My Schedule</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/appointments">
                    <i class="fas fa-fw fa-calendar-check"></i>
                    <span>Create Appointment</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patients">
                    <i class="fas fa-fw fa-stethoscope"></i>
                    <span>Patients</span></a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="/invoices">
                    <i class="fas fa-fw fa-file-invoice"></i>
                    <span>Invoices</span></a>
            </li>






                    <li class="nav-item">
                <a class="nav-link" href="/roombooking">
                    <i class="fas fa-fw fa-bed"></i>
                    <span>Book a Rooom</span></a>
            </li>
                    <li class="nav-item">
                <a class="nav-link" href="/roomadmissions">
                    <i class="fas fa-fw fa-bed"></i>
                    <span>Boookings</span></a>
            </li>

{% elif role == "patient" %}
            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="/">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Homepage</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/appointments">
                    <i class="fas fa-fw fa-calendar-check"></i>
                    <span>Appointments</span></a>
            </li>
           <li class="nav-item">
                <a class="nav-link" href="/profile">
                    <i class="fas fa-fw fa-archive"></i>
                    <span>Profile</span></a>
            </li>



    {% endif %}


             <li class="nav-item">
                <a class="nav-link" href="/logout">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Logout</span></a>
            </li>
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->


        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column" style="margin-left:5px!important;padding-left:15px!important;">
<br >
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>

                </button>
            </div>
                {% else %}
             <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>

                </button>
            </div>
                {% endif %}
            {% endfor %}
        {% endif %}

    {% endwith %}


            {% block content %} {% endblock %}
        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap_suggest.js') }}"></script>

    {% block scripts %}
{% endblock %}
</body>

</html>

website/templates/manage.html
{% extends 'base.html' %}
{% block title%} Manage {% endblock %}
{% block content %}

<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Manage Staff</h1>





    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Manage Hospital Staff</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Staff_ID</th>
                            <th>Staff First Name</th>
                            <th>Staff Surname</th>
                            <th>Staff_Specification</th>
                            <th>Staff_Role</th>
                            <th>Staff_Email</th>

                            

                        </tr>
                    </thead>
                    <tbody>
                
                        {% for staff in Hospital_Staff %}
  
                        <tr>
                            <td>{{ staff.Staff_ID }}</td>
                            <td>{{ staff.Name }}</td>
                            <td>{{ staff.Surname }}</td>
                            <td>{{ staff.Specification.Title }}</td>
                            <td>{{ staff.Role1.Description }}</td>
                            <td>{{ staff.EMail }}</td>

                    
                            <td>
                                <form action="{{ url_for('views.deletestaff', id=staff.Staff_ID) }}" method="POST">
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    
                                </form>
                                
                            </td>
                        </tr>

                        {%endfor%}
                        
                       
                    </tbody>
                </table>
            </div>
        </div>
    </div>

                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myhsadd">Add a Hospital Staff</button>


                    <!-- docadd -->
                    <div id="myhsadd" class="modal fade" role="dialog">
                      <div class="modal-dialog">

                        <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header">
                            <h3 align="center">Enter Staff Details</h3>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <!-- <h4 class="modal-title">Modal Header</h4> -->
                          </div>
                          <div class="modal-body">
                            <form method="post">
                                <div class="form-group">
                                    <label for="staff_name">Staff First Name</label>
                                    <input 
                                        type="text" 
                                        class="form-control" 
                                        id="Name"
                                        name="Name"
                                        placeholder="Enter Staff Name"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="staff_surname">Staff Surname</label>
                                    <input 
                                        type="text" 
                                        class="form-control" 
                                        id="Surname"
                                        name="Surname"
                                        placeholder="Enter Staff Surname"
                                    />
                                </div>
                                
                                <div class="form-group">
                                    <label for="specification_type">Specialization Type</label>
                                    <select class="form-control" 
                                        id="Specification_ID"
                                        name="Specification_ID"
                                        placeholder="Select Specialization Type">
                                    <!-- <option value="blank"></option> -->
                                        {% for specification in specifications %}
                                    <option value="{{ specification.Specification_ID }}" selected>{{ specification.Title }}</option >


                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="role_type">role Type</label>
                                    <select class="form-control" 
                                        id="Role"
                                        name="Role"
                                        placeholder="Select role Type">
                                    <!-- <option value="blank"></option> -->
                                        {% for role in roles %}
                                    <option value="{{ role.Role }}" selected>{{ role.Description }}</option >
                                    {% endfor %}
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="staff_EMail">Email</label>
                                    <input 
                                        type="Email" 
                                        class="form-control" 
                                        id="EMail"
                                        name="EMail"
                                        placeholder="Enter Staff EMail"
                                    />
                                </div>

                                <div class="form-group">
                                    <label for="Staff_Password">Password</label>
                                    <input 
                                        type="Password" 
                                        class="form-control" 
                                        id="Password"
                                        name="Password"
                                        placeholder="Enter Staff Password"
                                    />
                                </div>
                                
                                <br/>
                                <button type="submit" class="btn btn-primary">Save Details</button>
                            </form>
                        </div>
                        <!-- <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div> -->
            </div>

        </div>
    </div>
                   
</div>
                <!-- /.container-fluid -->

{% endblock %}




            